steps:
  - id: tf init
    name: hashicorp/terraform:0.12.24
    dir: ./src/infrastructure
    entrypoint: sh
    args:
      - -c
      - |
        echo ""
        echo "[INIT]"            
        terraform init

  - id: tf plan
    name: hashicorp/terraform:0.12.24
    dir: ./src/infrastructure
    entrypoint: sh
    args:
      - -c
      - |
        echo ""
        echo "[PLAN]"
        terraform plan

  - id: tf apply
    name: hashicorp/terraform:0.12.24
    dir: ./src/infrastructure
    entrypoint: sh
    args:
      - -c
      - |
        echo ""
        echo "[APPLY]"
        if [ -n "$_BASE_BRANCH" ]; then
          echo 'Skip. This is a Pull Request.'      
        else
          terraform apply -auto-approve
        fi
timeout: 1800s
