steps:
  # Preparation
  - id: get-latest-kubectl
    name: gcr.io/cloud-builders/gcloud
    volumes:
      - name: shared
        path: /shared
    entrypoint: sh
    args:
      - -c
      - |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/kubectl
        chmod +x kubectl
        mv kubectl /shared/kubectl

  # Cert Manager
  - id: cert-manager
    name: gcr.io/cloud-builders/gcloud
    volumes:
      - name: shared
        path: /shared
    entrypoint: sh
    args:
      - -c
      - |
        alias kubectl=/shared/kubectl
        gcloud container clusters get-credentials challenges --region asia-northeast1 --project $PROJECT_ID        

        kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.4/cert-manager.yaml

        kubectl -n cert-manager get secrets/cert-manager-sa-key > /dev/null
        if [ $? -ne 0  ]; then
          gcloud iam service-accounts keys create cert-manager-key.json \
            --iam-account cert-manager@$PROJECT_ID.iam.gserviceaccount.com

          kubectl create secret generic cert-manager-sa-key \
            --from-file=cert-manager-key.json \
            --namespace=cert-manager
        fi

        sed -i "s/\$$PROJECT_ID/$PROJECT_ID/g" ./cert-manager/issuer.yaml
        kubectl apply -f ./cert-manager/issuer.yaml

        DOMAIN_BASE=$(gcloud dns managed-zones describe default --project $PROJECT_ID --format 'value(dnsName)' | sed 's/\.$//')
        sed -i "s/\$$DOMAIN_BASE/$$DOMAIN_BASE/g" ./cert-manager/certificate.yaml
        kubectl apply -f ./cert-manager/certificate.yaml

  # Challenge: Burp
  - id: build-challenge-burp
    name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=gcr.io/$PROJECT_ID/challenges/burp/app
      - --context=./challenges/burp/app
      - --cache=true
      - --cache-ttl=7200h

  - id: deploy-challenge-burp
    name: gcr.io/cloud-builders/gcloud
    volumes:
      - name: shared
        path: /shared
    entrypoint: sh
    args:
      - -c
      - |
        alias kubectl=/shared/kubectl
        gcloud container clusters get-credentials challenges --region asia-northeast1 --project $PROJECT_ID        

        sed -i "s/\$$PROJECT_ID/$PROJECT_ID/g" ./challenges/burp/deployment.yaml
        kubectl apply -f ./challenges/burp/deployment.yaml
        kubectl apply -f ./challenges/burp/service.yaml

  # Challenge: bregex
  - id: build-challenge-bregex-app
    name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=gcr.io/$PROJECT_ID/challenges/bregex/app
      - --context=./challenges/bregex/app
      - --cache=true
      - --cache-ttl=7200h

  - id: build-challenge-bregex-nginx
    name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=gcr.io/$PROJECT_ID/challenges/bregex/nginx
      - --context=./challenges/bregex/nginx
      - --cache=true
      - --cache-ttl=7200h

  - id: deploy-challenge-bregex
    name: gcr.io/cloud-builders/gcloud
    volumes:
      - name: shared
        path: /shared
    entrypoint: sh
    args:
      - -c
      - |
        alias kubectl=/shared/kubectl
        gcloud container clusters get-credentials challenges --region asia-northeast1 --project $PROJECT_ID        

        sed -i "s/\$$PROJECT_ID/$PROJECT_ID/g" ./challenges/bregex/deployment.yaml
        kubectl apply -f ./challenges/bregex/deployment.yaml
        kubectl apply -f ./challenges/bregex/service.yaml

  # Challenge: Cache Poisoning
  - id: build-challenge-cache-poisoning-app
    name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=gcr.io/$PROJECT_ID/challenges/cacge-poisoning/app
      - --context=./challenges/cache-poisoning/app
      - --cache=true
      - --cache-ttl=7200h

  - id: build-challenge-cache-poisoning-nginx
    name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=gcr.io/$PROJECT_ID/challenges/cacge-poisoning/nginx
      - --context=./challenges/cache-poisoning/nginx
      - --cache=true
      - --cache-ttl=7200h

  - id: deploy-challenge-cache-poisoning
    name: gcr.io/cloud-builders/gcloud
    volumes:
      - name: shared
        path: /shared
    entrypoint: sh
    args:
      - -c
      - |
        alias kubectl=/shared/kubectl
        gcloud container clusters get-credentials challenges --region asia-northeast1 --project $PROJECT_ID        

        sed -i "s/\$$PROJECT_ID/$PROJECT_ID/g" ./challenges/cache-poisoning/deployment.yaml
        kubectl apply -f ./challenges/cache-poisoning/deployment.yaml
        kubectl apply -f ./challenges/cache-poisoning/service.yaml

  # Default App
  - id: hello-app
    name: gcr.io/cloud-builders/gcloud
    volumes:
      - name: shared
        path: /shared
    entrypoint: sh
    args:
      - -c
      - |
        alias kubectl=/shared/kubectl
        gcloud container clusters get-credentials challenges --region asia-northeast1 --project $PROJECT_ID
        kubectl apply -f ./hello-app/deployment.yaml
        kubectl apply -f ./hello-app/service.yaml

  # Ingress
  - id: ingress
    name: gcr.io/cloud-builders/gcloud
    volumes:
      - name: shared
        path: /shared
    entrypoint: sh
    args:
      - -c
      - |
        alias kubectl=/shared/kubectl
        gcloud container clusters get-credentials challenges --region asia-northeast1 --project $PROJECT_ID

        DOMAIN_BASE=$(gcloud dns managed-zones describe default --project $PROJECT_ID --format 'value(dnsName)' | sed 's/\.$//')        
        sed -i "s/\$$DOMAIN_BASE/$$DOMAIN_BASE/g" ./ingress/ingress.yaml
        kubectl apply -f ./ingress/ingress.yaml
