steps:
  - id: get-latest-kubectl
    name: gcr.io/cloud-builders/gcloud
    volumes:
      - name: shared
        path: /shared
    entrypoint: sh
    args:
      - -c
      - |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/kubectl
        chmod +x kubectl
        mv kubectl /shared/kubectl

  - id: cert-manager
    name: gcr.io/cloud-builders/gcloud
    volumes:
      - name: shared
        path: /shared
    entrypoint: sh
    args:
      - -c
      - |
        alias kubectl=/shared/kubectl
        gcloud container clusters get-credentials challenges --region asia-northeast1 --project $PROJECT_ID        

        kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.4/cert-manager.yaml

        kubectl -n cert-manager get secrets/cert-manager-sa-key > /dev/null
        if [ $? -ne 0  ]; then
          gcloud iam service-accounts keys create cert-manager-key.json \
            --iam-account cert-manager@$PROJECT_ID.iam.gserviceaccount.com

          kubectl create secret generic cert-manager-sa-key \
            --from-file=cert-manager-key.json \
            --namespace=cert-manager
        fi

        sed -i "s/\$$PROJECT_ID/$PROJECT_ID/g" ./cert-manager/issuer.yaml
        kubectl apply -f ./cert-manager/issuer.yaml

        DOMAIN_BASE=$(gcloud dns managed-zones describe default --project $PROJECT_ID --format 'value(dnsName)' | sed 's/\.$//')
        sed -i "s/\$$DOMAIN_BASE/$$DOMAIN_BASE/g" ./cert-manager/certificate.yaml
        kubectl apply -f ./cert-manager/certificate.yaml

  - id: hello-app
    name: gcr.io/cloud-builders/gcloud
    volumes:
      - name: shared
        path: /shared
    entrypoint: sh
    args:
      - -c
      - |
        alias kubectl=/shared/kubectl
        gcloud container clusters get-credentials challenges --region asia-northeast1 --project $PROJECT_ID        
        kubectl apply -f ./hello-app/deployment.yaml
        kubectl apply -f ./hello-app/service.yaml

  - id: ingress
    name: gcr.io/cloud-builders/gcloud
    volumes:
      - name: shared
        path: /shared
    entrypoint: sh
    args:
      - -c
      - |
        alias kubectl=/shared/kubectl
        gcloud container clusters get-credentials challenges --region asia-northeast1 --project $PROJECT_ID

        DOMAIN_BASE=$(gcloud dns managed-zones describe default --project $PROJECT_ID --format 'value(dnsName)' | sed 's/\.$//')        
        sed -i "s/\$$DOMAIN_BASE/$$DOMAIN_BASE/g" ./ingress/ingress.yaml
        kubectl apply -f ./ingress/ingress.yaml
