apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-template-confusion-deployment
spec:
  selector:
    matchLabels:
      app: template-confusion
      type: challenge
  template:
    metadata:
      labels:
        app: template-confusion
        type: challenge
    spec:
      containers:
        - name: app
          image: gcr.io/$PROJECT_ID/challenges/template-confusion/app:latest
          imagePullPolicy: Always
        - name: nginx
          image: gcr.io/$PROJECT_ID/challenges/template-confusion/nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
