apiVersion: v1
kind: Service
metadata:
  name: challenge-template-confusion-service
spec:
  type: NodePort
  selector:
    app: template-confusion
    type: challenge
  ports:
    - port: 80
      targetPort: 80
