apiVersion: v1
kind: Service
metadata:
  name: challenge-cache-poisoning-service
spec:
  type: NodePort
  selector:
    app: cache-poisoning
    type: challenge
  ports:
    - port: 80
      targetPort: 80
