apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-burp-deployment
spec:
  selector:
    matchLabels:
      app: burp
      type: challenge
  template:
    metadata:
      labels:
        app: burp
        type: challenge
    spec:
      containers:
        - name: app
          image: gcr.io/$PROJECT_ID/challenges/burp/app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
